# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
sudo: required
dist: trusty
matrix:
  include:
    - os: linux
      before_script:
        - "export DISPLAY=:99.0"
        - "sh -e /etc/init.d/xvfb start"
        - sleep 3 # give xvfb some time to start
      addons:
        apt:
          packages:
            - cmake
            - cmake-data
            - qtdeclarative5-dev
            - qtdeclarative5-qtquick2-plugin
            - qtdeclarative5-dialogs-plugin
            - qtdeclarative5-controls-plugin
            - qtdeclarative5-quicklayouts-plugin
      julia: release
    - os: osx
      env:
        - CMAKE_PREFIX_PATH=/usr/local/opt/qt5
      before_install:
        - brew update
        - brew install qt5
      compiler: "clang"
      julia: nightly
notifications:
  email: true
