# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
sudo: required
dist: trusty
matrix:
  include:
    - os: linux
      addons:
        apt:
          packages:
            - cmake
            - cmake-data
            - qtdeclarative5-dev
      julia: release
    - os: osx
      env:
        - CMAKE_PREFIX_PATH=/usr/local/opt/qt5
      before_install:
        - brew update
        - brew install qt5
      compiler: "clang"
      julia: nightly
notifications:
  email: true
