# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
sudo: required
dist: trusty
matrix:
  include:
    - os: linux
      env:
        - QML_SKIP_GUI_TESTS=0
      before_script:
        - "export DISPLAY=:99.0"
        - "sh -e /etc/init.d/xvfb start"
        - sleep 3 # give xvfb some time to start
        - "export GALLIUM_DRIVER=\"softpipe\""
      julia: release
    - os: osx
      compiler: "clang"
      julia: nightly
notifications:
  email: true
